language: python
python:
- '2.7'
install:
- sudo bash scripts/vagrant/init_environment.sh
- sudo /usr/local/bin/taskd server --data /var/taskd --daemon
- sudo chmod -R 777 ./
- sudo chmod -R 777 /var/taskd
before_script:
- gem install travis-artifacts
after_script:
- travis-artifacts upload --path logs/twweb.log
- travis-artifacts upload --path logs/twweb.error.log
- bash scripts/travis/upload_screenshots.sh
services:
- memcached
- redis-server
script:
- bash scripts/travis/run_tests.sh
notifications:
  email: true
env:
  global:
  - ARTIFACTS_S3_BUCKET=inthe-am-travis-artifacts
  - secure: O4E8E5n56RLDD8k6puAHe3EwQ4kUTK01b8DtcD71kyQrmsoPj6ArSzSDQ346IE37nV/KkzbH2lytNWY2MePnF/wl3PI3mzKPmNOx6xZn8xstJ44ul37pNIjEEje4zB3XeSFAtc9K6le0dwt9J8Fr3X8UoSg7qgvuRtPQL7L8diU=
  - secure: B8ctbrU5GlVZrOhcIyS1IqKhLMMl2e9GjIZpm3utnnLZO59Ym2AB0Mau81wryKmC5mLCQRZbBLTh1nCym7lXapeU1aYDyUVfNWl9V4gpioymjq4+cN5kAmJxibkfAITkimwkTPylRjTYEpceXSB4GQSy8SFm3don/Q8+d/O8PKs=
  - secure: AoJXZaLC5kbf8O5fHX4x9cq2+o+W3W0j819buw0m+qdlNjyuHcUMtW+kc3M3clGWmJs7UANP6+YfXGpRhIFZdM1izXREupfoiCArKecDVZKVVCCCaT9RE6Qcw9uBwGa63goVNy/e285qhSoNBr1cPHsN46ydrMuX7g0rys5mOZo=
  - secure: jBOlkGEC3JaAzEf7+tYLrbfTDjwrx9MbDWadEOrpbl5b9Ue8n2KF23IBUZm/1LcmZIyWWcaFORNPLox3kXx2wyHrpqE96NYSW2XVzsPalNO2wlbrlVlnebTivulgu7nMQ/UgF1yFzYPHwBh3Olf35EzPnWVUpOrWE1qJgM7PcEg=
  - secure: WXqmIfL4/8uy6daZxQ1iuLTi1r7/cQ9+fIbqRkds+MgYBQyfjfokTiyRx+4G7CS0ScDfmmz2s6r2SHlSsO+fAcaJihguKT0u1fmtHiHD6t0TtagqBpcOd4ZjBGf7AnjQQkFj82ei7ydYQAdzlooymPS2U+LP2dZ6OE/n2G/EUq8=
  - secure: YrXxu+iCZDLeVtBP6VGA9QB0/aIPiXd/a42ncN32MZxgCuj5lzKauM2BVNdfhY28YsDyn5ss+FP1ZAujrO4thrVnacfh+79G01JDhJb2++vPeo0R9Atz0hgO24ImKSV5lltk/OMTvKga9D9+x39RlHfeid7ShR7qBvn9wbyBf6w=
  - secure: XZfSZv21G5E2EPqiIqCKMvrJnd+0tzfHqP961pBRUxST9y7A/QuJI/oOCuOCjCOyXEhc0S5D3PL+9Uo+v9EIuHN06eYcS935sQ9SZsPOGo8EiPStBL0NIoNEqXmcrrBNnwNaYh3UHql5qV5/4Qlg+t4krKMuQrw/hWEHbx+mAkU=
