# make sure to `git submodule update --init` before building images
version: '3'
services:
  web:
    restart: always
    build:
      # image: intheam_django
      context: ./
      dockerfile: ./docker/django/Dockerfile
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
      - ./external_python_modules:/external_python_modules
      - django-static-assets:/django-static
      - taskd-data:/taskserver_data:ro
    networks:
      - backend
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && uwsgi --ini uwsgi.ini"
  nginx:
    restart: always
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    volumes:
      - ./logs:/app/logs/
      - django-static-assets:/app/static:ro
    networks:
      - backend
    links:
      - web:web
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./docker/backups/postgresql:/backup
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - backend
  memcached:
    image: 'bitnami/memcached:latest'
    networks:
      - backend
  taskd:
    build:
      dockerfile: ./docker/taskd/Dockerfile
      context: ./
    networks:
      - backend
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - taskd-data:/var/taskd
volumes:
  db-data:
  django-static-assets:
  task-data:
  taskd-data:
networks:
  backend:
