# make sure to `git submodule update --init` before building images
version: '3'
services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
      - sse:sse
    environment:
      - DEBUG=1
      - SUPERVISORD_CONFIG=./docker/django/supervisord.conf
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
      - django-static-assets:/django-static
    networks:
      - backend
  sse:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    environment:
      - SUPERVISORD_CONFIG=./docker/django/supervisord.sse.conf
    expose:
      - "8001"
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
    networks:
      - backend
  celery:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    environment:
      - SUPERVISORD_CONFIG=./docker/django/supervisord.celery.conf
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
    networks:
      - backend
  nginx:
    restart: always
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    volumes:
      - django-static-assets:/app/static:ro
    networks:
      - backend
    links:
      - web:web
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
  redis:
    restart: always
    image: redis:latest
    networks:
      - backend
  memcached:
    image: 'bitnami/memcached:latest'
    networks:
      - backend
  taskd:
    build:
      dockerfile: ./docker/taskd/Dockerfile
      context: ./
    networks:
      - backend
    links:
      - redis:redis
    volumes:
      - taskd-data:/var/taskd
volumes:
  db-data:
    external: true
  task-data:
    external: true
  taskd-data:
    external: true
  django-static-assets:
networks:
  backend:
