# make sure to `git submodule update --init` before building images

version: '2'
services:
  web:
    restart: always
    build:
      # image: intheam_django
      context: ./
      dockerfile: ./docker/django/Dockerfile
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
    env_file: .env
    volumes:
      - ./:/data/web
      - ./external_python_modules:/external_python_modules
    command: /usr/bin/gunicorn inthe_am.wsgi:application -w 2 -b :8000
  nginx:
    restart: always
    build:
      dockerfile: docker/Dockerfile
      context: ember/
    ports:
      - "80:80"
    volumes_from:
      - web
    volumes:
      - ./logs:/app/logs/
    links:
      - web:web
  zapier:
    restart: always
    build:
      dockerfile: ../docker/zapier/Dockerfile
      context: zapier/
    volumes_from:
      - web
    volumes:
      - ./logs:/app/logs/
    links:
      - web:web
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/backups/postgresql:/backup
    env_file:
      - .env
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  memcached:
    image: 'bitnami/memcached:latest'

  taskd:
    build: ./docker/taskd
    volumes:
      - ./docker/data:/var/taskd

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"
